version: '3'

services:
 postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
   - POSTGRES_PASSWORD=mysecretpassword
   - POSTGRES_USER=postgres
   - POSTGRES_DB=postgres
 golang:
  build: .
  restart: on-failure
  ports:
   - "8080:8080"
  environment:
   - DATABASE_URL=postgres://postgres:mysecretpassword@gographql_postgres_1:5432/postgres?sslmode=disable
  depends_on:
   - postgres
 spring:
  image: borapaul/springapp:1.4
  ports:
   - "9090:8080"
  environment:
  - SPRING_DATASOURCE_URL=jdbc:postgresql://gographql_postgres_1:5432/postgres
  - SPRING_DATASOURCE_USERNAME=postgres
  - SPRING_DATASOURCE_PASSWORD=mysecretpassword
  depends_on:
   - postgres