// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCompany struct {
	ID         *string        `json:"id"`
	LocationID *string        `json:"locationID"`
	Name       string         `json:"name"`
	Location   *NewLocation   `json:"location"`
	Employees  []*NewEmployee `json:"employees"`
}

type NewEmployee struct {
	Location  *NewLocation `json:"location"`
	Name      string       `json:"name"`
	Age       *int         `json:"age"`
	Gender    *string      `json:"gender"`
	CompanyID *string      `json:"companyID"`
}

type NewLocation struct {
	Longitude int    `json:"longitude"`
	Latitude  int    `json:"latitude"`
	City      string `json:"city"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
